/*
 * This file is generated by jOOQ.
 */
package com.github.krystiankowalik.jooqexample.domain;


import com.github.krystiankowalik.jooqexample.domain.tables.Comments;
import com.github.krystiankowalik.jooqexample.domain.tables.Posts;

import javax.annotation.Generated;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables of the <code>testdb</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index COMMENTS_POST_ID = Indexes0.COMMENTS_POST_ID;
    public static final Index COMMENTS_PRIMARY = Indexes0.COMMENTS_PRIMARY;
    public static final Index POSTS_PRIMARY = Indexes0.POSTS_PRIMARY;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Indexes0 {
        public static Index COMMENTS_POST_ID = Internal.createIndex("POST_ID", Comments.COMMENTS, new OrderField[] { Comments.COMMENTS.POST_ID }, false);
        public static Index COMMENTS_PRIMARY = Internal.createIndex("PRIMARY", Comments.COMMENTS, new OrderField[] { Comments.COMMENTS.ID }, true);
        public static Index POSTS_PRIMARY = Internal.createIndex("PRIMARY", Posts.POSTS, new OrderField[] { Posts.POSTS.ID }, true);
    }
}
