/*
 * This file is generated by jOOQ.
 */
package com.github.krystiankowalik.jooqexample.domain;


import com.github.krystiankowalik.jooqexample.domain.tables.Comments;
import com.github.krystiankowalik.jooqexample.domain.tables.Posts;
import com.github.krystiankowalik.jooqexample.domain.tables.records.CommentsRecord;
import com.github.krystiankowalik.jooqexample.domain.tables.records.PostsRecord;

import javax.annotation.Generated;

import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.UniqueKey;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables of 
 * the <code>testdb</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------

    public static final Identity<CommentsRecord, Integer> IDENTITY_COMMENTS = Identities0.IDENTITY_COMMENTS;
    public static final Identity<PostsRecord, Integer> IDENTITY_POSTS = Identities0.IDENTITY_POSTS;

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<CommentsRecord> KEY_COMMENTS_PRIMARY = UniqueKeys0.KEY_COMMENTS_PRIMARY;
    public static final UniqueKey<PostsRecord> KEY_POSTS_PRIMARY = UniqueKeys0.KEY_POSTS_PRIMARY;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------

    public static final ForeignKey<CommentsRecord, PostsRecord> COMMENTS_IBFK_1 = ForeignKeys0.COMMENTS_IBFK_1;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Identities0 {
        public static Identity<CommentsRecord, Integer> IDENTITY_COMMENTS = Internal.createIdentity(Comments.COMMENTS, Comments.COMMENTS.ID);
        public static Identity<PostsRecord, Integer> IDENTITY_POSTS = Internal.createIdentity(Posts.POSTS, Posts.POSTS.ID);
    }

    private static class UniqueKeys0 {
        public static final UniqueKey<CommentsRecord> KEY_COMMENTS_PRIMARY = Internal.createUniqueKey(Comments.COMMENTS, "KEY_COMMENTS_PRIMARY", Comments.COMMENTS.ID);
        public static final UniqueKey<PostsRecord> KEY_POSTS_PRIMARY = Internal.createUniqueKey(Posts.POSTS, "KEY_POSTS_PRIMARY", Posts.POSTS.ID);
    }

    private static class ForeignKeys0 {
        public static final ForeignKey<CommentsRecord, PostsRecord> COMMENTS_IBFK_1 = Internal.createForeignKey(Keys.KEY_POSTS_PRIMARY, Comments.COMMENTS, "COMMENTS_ibfk_1", Comments.COMMENTS.POST_ID);
    }
}
