/*
 * This file is generated by jOOQ.
 */
package com.github.krystiankowalik.jooqexample.domain;


import com.github.krystiankowalik.jooqexample.domain.tables.Comments;
import com.github.krystiankowalik.jooqexample.domain.tables.Posts;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in testdb
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>testdb.COMMENTS</code>.
     */
    public static final Comments COMMENTS = Comments.COMMENTS;

    /**
     * The table <code>testdb.POSTS</code>.
     */
    public static final Posts POSTS = Posts.POSTS;
}
