/*
 * This file is generated by jOOQ.
 */
package com.github.krystiankowalik.jooqexample.domain;


import com.github.krystiankowalik.jooqexample.domain.tables.Comments;
import com.github.krystiankowalik.jooqexample.domain.tables.Posts;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Testdb extends SchemaImpl {

    private static final long serialVersionUID = 312657395;

    /**
     * The reference instance of <code>testdb</code>
     */
    public static final Testdb TESTDB = new Testdb();

    /**
     * The table <code>testdb.COMMENTS</code>.
     */
    public final Comments COMMENTS = Comments.COMMENTS;

    /**
     * The table <code>testdb.POSTS</code>.
     */
    public final Posts POSTS = Posts.POSTS;

    /**
     * No further instances allowed
     */
    private Testdb() {
        super("testdb", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            Comments.COMMENTS,
            Posts.POSTS);
    }
}
